config/routes.rb
Rails.application.routes.draw do

  root 'flights#index'
  
  resources :flights,      only: [:show]
  resources :bookings,     only: [:new, :create, :show]

end

app/models/airport.rb
class Airport < ActiveRecord::Base
    has_many :departing_flights, class_name: "Flight", foreign_key: "from_airport_id"
    has_many :arriving_flights, class_name: "Flight", foreign_key: "to_airport_id"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  
  accepts_nested_attributes_for :passengers
  
  validates :flight_id, presence: true
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :to_airport, class_name: "Airport"
  belongs_to :from_airport, class_name: "Airport"
  
  has_many :bookings
  
  validates :departing_time, presence: true
  validates :duration, presence: true
  validates :to_airport_id, presence: true
  validates :from_airport_id, presence: true
    
  def date_formatted
    departing_time.strftime("%m/%d/%Y")
  end
  
  def datetime_formatted
    departing_time.strftime("%m/%d/%Y %I:%M%p")
  end
  
  def matches_search?(to,from,time)
      if self.to_airport.id == to.to_i && self.from_airport.id == from.to_i && self.departing_time.beginning_of_day == time.to_datetime
          true
      else
          false
      end
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :booking
  
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    
    @flight = Flight.find(params[:flight_id])
    @num_tickets = params[:num_tickets_id].to_i
    @num_tickets.times { @booking.passengers.build }
  end
  
  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      @emails = booking_params[:passengers_attributes].values.map { |passenger| passenger["email"] }
      @emails.each do |email|
        PassengerMailer.thank_you_email(email, @booking).deliver
      end
      
      flash[:success] = "Booking Created!"
      redirect_to @booking
    else
      flash.now[:error] = "Booking not saved"
      render 'new'
    end
  end
  
  def show
    @booking = Booking.find(params[:id])
  end
  
  private
  
  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
  end
  
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map { |airport| [airport.code, airport.id] }
    @date_options = (Flight.all.map { |flight| [flight.date_formatted, flight.departing_time.beginning_of_day ] }).uniq.sort
    
    to = params[:to_id]
    from = params[:from_id]
    time = params[:date_id]
    @num_tickets = params[:num_tickets_id]
    @search_results = Flight.all.select { |flight| flight.matches_search?(to,from,time) }
    #flash.now[:error] = "No flights match criteria" if @search_results.empty?
  end
  
  def show
    @flight = Flight.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Complete Booking</h1>

<%= form_for @booking do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <%= f.hidden_field(:flight_id, :value => @flight.id) %>
  <h3><%= @flight.datetime_formatted %></h3>
  <ul>
      <li>Departing From: <%= @flight.from_airport.code %></li>
      <li>Arriving At: <%= @flight.to_airport.code %></li>
      <li>Duration: <%= @flight.duration %></li>
  </ul>

    <p>Add Passenger</p>
    <%= f.fields_for :passengers do |passenger_f| %>
      <%= f.label :name %>
      <%= passenger_f.text_field :name %>
      <%= f.label :email %>
      <%= passenger_f.text_field :email %>
      <br>
    <% end %>

  <br>
  <%= f.submit("Submit Booking") %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking <%= @booking.id %></h1>

<br>

<ul>
  <li><%= @booking.flight.datetime_formatted %></li>
  <li>Departing From: <%= @booking.flight.from_airport.code %></li>
  <li>Arriving At: <%= @booking.flight.to_airport.code %></li>
  <li>Duration: <%= @booking.flight.duration %></li>
</ul>

<br>

<h3>Passengers:</h3>

<ul>
  <% @booking.passengers.each do |passenger| %>
    <li><%= passenger.name %></li>
  <% end %>
</ul>

app/views/flights/index.html.erb
<h1>Flight Booker</h1>



<%= form_tag(root_path, method: "get") do %>
  <%= label_tag(:from, "Departing Airport:") %>
  <%= select_tag(:from_id, options_for_select(@airport_options)) %>
  <%= label_tag(:to, "Arriving Airport:") %>
  <%= select_tag(:to_id, options_for_select(@airport_options)) %>
  <%= label_tag(:num_tickets, "Number of Tickets:") %>
  <%= select_tag(:num_tickets_id, options_for_select([1,2,3,4])) %>
  <%= label_tag(:date, "Date of Departure:") %>
  <%= select_tag(:date_id, options_for_select(@date_options)) %>
  <%= submit_tag("Search") %>
<% end %>


<% if @search_results.any? %>
  <h1>Search Results</h1>
  <%= form_tag(new_booking_path, method: "get") do %>
    <% @search_results.each do |result| %>
      <%= radio_button_tag("flight_id", result.id) %>
      <%= hidden_field_tag(:num_tickets_id, @num_tickets) %>
      <%= result.datetime_formatted %>
      <ul>
        <li>Departing Airport: <%= result.from_airport.code %></li>
        <li>Arriving Airport: <%= result.to_airport.code %></li>
      </ul>
    <% end %>
    <%= submit_tag("Select Flight") %>
  <% end %>
<% end %>

app/views/flights/show.html.erb
<h1>Flight <%= @flight.id %></h1>

<br>

<ul>
  <li><%= @flight.datetime_formatted %></li>
  <li>Departing From: <%= @flight.from_airport.code %></li>
  <li>Arriving At: <%= @flight.to_airport.code %></li>
  <li>Duration: <%= @flight.duration %></li>
</ul>

<br>

<h3>Passengers:</h3>

<ul>
  <% @flight.passengers.each do |passenger| %>
    <li><%= passenger.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>